// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAvxT0rKnh7Cg2q_tATeKwXj5EqCeafbI',
    appId: '1:111932876065:web:9ec6b0bae59e22a2a3ca60',
    messagingSenderId: '111932876065',
    projectId: 'fir-fire-auth-967e5',
    authDomain: 'fir-fire-auth-967e5.firebaseapp.com',
    storageBucket: 'fir-fire-auth-967e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIpam9nRm0DJITThkI3OAbLKGXAM4jJM',
    appId: '1:111932876065:android:a55b91de98ccaf8aa3ca60',
    messagingSenderId: '111932876065',
    projectId: 'fir-fire-auth-967e5',
    storageBucket: 'fir-fire-auth-967e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiWrgESF1jNR_PSX0y6VO0v59sFA0ZscA',
    appId: '1:111932876065:ios:084461fa0d7e2ee5a3ca60',
    messagingSenderId: '111932876065',
    projectId: 'fir-fire-auth-967e5',
    storageBucket: 'fir-fire-auth-967e5.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiWrgESF1jNR_PSX0y6VO0v59sFA0ZscA',
    appId: '1:111932876065:ios:97ee48599bb834bca3ca60',
    messagingSenderId: '111932876065',
    projectId: 'fir-fire-auth-967e5',
    storageBucket: 'fir-fire-auth-967e5.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseauth.RunnerTests',
  );
}
